controller_manager:
  ros__parameters:
    update_rate: 100

    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    can_controller:
      type: forward_command_controller/ForwardCommandController

    



can_controller:
  ros__parameters:
    joints:
      - front_left
      - middle_left
      - back_left
      - front_right
      - middle_right
      - back_right
    command_interfaces: 
      - velocity


